### PR TITLE
mingw-w64-asciidoctor: install to sdk

### PR DESCRIPTION
**Pull request by dennisameling**
In a recent change, GfW switched from the homegrown `-asciidoctor-extensions` package to the MSYS2-provided `-asciidoctor` one, as there's no need for the former nowadays.

The changes from https://github.com/git-for-windows/git-sdk-arm64/pull/18 don't actually do much in this specific SDK, because unlike `git-sdk-64` and `git-sdk-32`, `-asciidoctor-extensions` was never installed on `git-sdk-arm64` in the first place.

This commit installs `-asciidoctor` and its dependencies:

mingw-w64-clang-aarch64-gdbm-1.19-3
mingw-w64-clang-aarch64-libyaml-0.2.5-2
mingw-w64-clang-aarch64-pdcurses-4.4.0-1
mingw-w64-clang-aarch64-ruby-3.1.5-1
mingw-w64-clang-aarch64-asciidoctor-2.0.23-1

Ref: https://github.com/git-for-windows/MINGW-packages/commit/907ead42e93c073c0a37b902df02ef0d08102a99

### CODE REVIEW

**Comment by dscho** [comment]
I'd prefer to have this as a patch to `update-via-pacman.ps1`, so that it is more obvious that a boring old workflow installed the packages, not a human being (which would have security implications).

So maybe you can change [this conditional clause](https://github.com/git-for-windows/git-sdk-arm64/blob/b2233317fb8b60bf1a5bbcb71e0855158428746c/update-via-pacman.ps1#L86-L110) to trigger on the absence of `var/lib/pacman/local/mingw-w64-*-asciidoctor-[0-9]*` instead of the presence of the corresponding `-asciidoctor-extensions` folder?

That should have the same effect as this here PR, but easier to reason about how safe the change is.

**Comment by dennisameling** [comment]
Works for me! Will update the script in the next 1-2 days as I wrap up some other work.

**Comment by rimrul** [comment]
> So maybe you can change [this conditional clause](https://github.com/git-for-windows/git-sdk-arm64/blob/b2233317fb8b60bf1a5bbcb71e0855158428746c/update-via-pacman.ps1#L86-L110) to trigger on the absence of `var/lib/pacman/local/mingw-w64-*-asciidoctor-[0-9]*` instead of the presence of the corresponding `-asciidoctor-extensions` folder?

Might make sense to split it into one part that removes `mingw-w64-asciidoctor-extensions` if installed and one part that installs `mingw-w64-asciidoctor` if missing.

**Comment by dennisameling** [comment]
Closing this MR in favor of https://github.com/git-for-windows/git-sdk-arm64/pull/20

**Pull request closed without merging**
