### PR TITLE
ca-certificates: reinstall to fix certificates

### PR DESCRIPTION
**Pull request by dennisameling**
Because CI pipelines run on x64 runners, some post-install scripts don't run there as the binaries are arm64.

Let's reinstall using `pacman -S mingw-w64-clang-aarch64-ca-certificates` to fix this situation.

Basically the same situation that we had last year: https://github.com/git-for-windows/git-sdk-arm64/pull/8

### CODE REVIEW

**Comment by dscho** [comment]
> Because CI pipelines run on x64 runners, some post-install scripts don't run there as the binaries are arm64.

I guess we need to change this, to use the self-hosted runners?

**Review by dscho — APPROVED** [review]

**Comment by dennisameling** [comment]
> I guess we need to change this, to use the self-hosted runners?

That'd be ideal. OK if I create a PR for that? I think that would just involve changing [this line](https://github.com/git-for-windows/git-sdk-arm64/blob/e2efde2cc17ad84ba82d8bfa9b0b5f0182ed1db0/.github/workflows/sync.yml#L20) to `runs-on: [Windows, ARM64]`, like we do [here](https://github.com/git-for-windows/git-for-windows-automation/blob/3c005eeaff11619f598ee1847fbb21593e050e95/.github/workflows/git-artifacts.yml#L46C77-L46C97), right?

**Comment by dscho** [comment]
> > I guess we need to change this, to use the self-hosted runners?
> 
> That'd be ideal. OK if I create a PR for that?

Absolutely!

> I think that would just involve changing [this line](https://github.com/git-for-windows/git-sdk-arm64/blob/e2efde2cc17ad84ba82d8bfa9b0b5f0182ed1db0/.github/workflows/sync.yml#L20) to `runs-on: [Windows, ARM64]`, like we do [here](https://github.com/git-for-windows/git-for-windows-automation/blob/3c005eeaff11619f598ee1847fbb21593e050e95/.github/workflows/git-artifacts.yml#L46C77-L46C97), right?

I think we also need the corresponding change to https://github.com/git-for-windows/gfw-helper-github-app/blob/3c89c37c7b9237a1a8becc1dc5e70c2e2ca3f059/GitForWindowsHelper/index.js#L42, something like:

```js
            && ['git-for-windows/git-for-windows-automation', 'git-for-windows/git-sdk-arm64'].includes(req.body.repository.full_name)
```

**Comment by dennisameling** [comment]
Sounds good, here's the first bit: https://github.com/git-for-windows/gfw-helper-github-app/pull/75

**Comment by dennisameling** [comment]
And the second part: https://github.com/git-for-windows/git-sdk-arm64/pull/14

**Pull request merged**
